[workspace]
resolver = "2"
members = [
    "crates/codepapr-core",
    "crates/codepapr-server",
    "crates/codepapr-cli",
    "packages/@codepapr/ui/src-tauri",
]
exclude = [
    ".cargo-vendor/c-sharp",
    ".cargo-vendor/css",
    ".cargo-vendor/html",
    ".cargo-vendor/json",
    ".cargo-vendor/kotlin",
    ".cargo-vendor/php",
    ".cargo-vendor/ruby",
    ".cargo-vendor/swift",
    ".cargo-vendor/sql",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["CodePapr"]
license = "MIT"
