/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // 语义色：全部映射到主题 CSS 变量（themeEngine 运行时注入）。
        deep: 'var(--bg-deep)',
        base: 'var(--bg-base)',
        raised: 'var(--bg-raised)',
        input: 'var(--bg-input)',
        hover: 'var(--bg-hover)',
        control: 'var(--bg-control, var(--border-strong))',
        fg: 'var(--foreground)',
        'fg-soft': 'var(--foreground-soft)',
        'fg-muted': 'var(--foreground-muted)',
        'fg-dim': 'var(--foreground-dim)',
        line: 'var(--border)',
        'line-strong': 'var(--border-strong)',
        accent: 'var(--accent)',
        'accent-soft': 'var(--accent-soft)',
        'accent-bg': 'var(--accent-bg)',
        'accent-text': 'var(--accent-text)',
        'accent-glow': 'var(--accent-glow)',
        ok: 'var(--green)',
        'ok-bg': 'var(--green-bg)',
        warn: 'var(--amber)',
        'warn-bg': 'var(--amber-bg)',
        danger: 'var(--red)',
        'danger-bg': 'var(--red-bg, var(--red))',
        info: 'var(--cyan)',
        'info-bg': 'var(--cyan-bg)',
        code: 'var(--code-bg)',
        'code-fg': 'var(--code-fg)',
        overlay: 'var(--overlay, rgba(0,0,0,0.6))',
        'toast-info': 'var(--toast-info, #0d1620)',
        'toast-ok': 'var(--toast-ok, #0d1a14)',
        'toast-warn': 'var(--toast-warn, #1c170b)',
        'toast-danger': 'var(--toast-danger, #1c0d12)',
        'ds-bg': '#0f1117',
        'ds-surface': '#1a1d27',
        'ds-border': '#2a2d3a',
        'ds-accent': '#6366f1',
        'ds-green': '#22c55e',
      },
    },
  },
  plugins: [],
};
