use flate2::read::GzDecoder;
#[cfg(not(windows))]
use reqwest::blocking::Client;
use serde_json::{json, Value};
use std::{
    env, fs,
    io::Read,
    path::{Path, PathBuf},
    process::Command,
    time::Duration,
};

#[path = "src/download_verification.rs"]
mod download_verification;
#[cfg(not(windows))]
use std::{io::Write, time::Instant};
use tar::Archive;
use xz2::read::XzDecoder;
use zip::ZipArchive;

#[derive(Clone, Copy)]
enum ArchiveKind {
    TarGz,
    TarXz,
    Zip,
}

const CLANGD_VERSION: &str = "22.1.6";
// 钉死到 milestone 版本：快照 URL 浮动且无法锁定哈希。
// 该 URL 同时存在于 src/download_verification.rs 的锁定清单中，升级时两处同步。
const JDTLS_DOWNLOAD_URL: &str =
    "https://download.eclipse.org/jdtls/milestones/1.54.0/jdt-language-server-1.54.0-202511261751.tar.gz";
const JAVA_RUNTIME_VERSION: &str = "21";
const NODE_RUNTIME_VERSION: &str = "v20.12.2";
// 钉死版本 + 锁定哈希（见 src/download_verification.rs），禁止使用 latest 浮动 URL。
const SQLS_VERSION: &str = "0.2.48";
const MARKSMAN_VERSION: &str = "2026-02-08";
#[cfg(not(windows))]
const DOWNLOAD_TIMEOUT: Duration = Duration::from_secs(300);
const MAX_DOWNLOAD_BYTES: usize = 600_000_000;
const NODE_LSP_PACKAGES: &[&str] = &[
    "typescript-language-server",
    "typescript",
    "vscode-langservers-extracted",
    "yaml-language-server",
    "pyright",
    "bash-language-server",
];

fn main() {
    register_build_inputs();
    ensure_generated_lsp_resource_dir();
    normalize_existing_bundled_lsp_assets();
    maybe_prepare_bundled_lsp_assets();
    maybe_publish_csharp_analyzer();
    tauri_build::build()
}

fn register_build_inputs() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-env-changed=CODEPAPR_SKIP_BUNDLED_LSP_PREPARE");
    println!("cargo:rerun-if-env-changed=CODEPAPR_SKIP_DOWNLOAD_CHECKSUM");
    register_rerun_if_changed(
        &manifest_dir()
            .join("tools")
            .join("CodePapr.CSharp.Analyzer"),
    );

    for path in [
        repo_root().join("package.json"),
        repo_root().join("package-lock.json"),
        ui_generated_lsp_resource_dir().join("bundle-manifest.json"),
    ] {
        if path.exists() {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn register_rerun_if_changed(path: &Path) {
    if should_skip_csharp_artifact_path(path) {
        return;
    }

    if path.is_file() {
        println!("cargo:rerun-if-changed={}", path.display());
        return;
    }

    let mut children = fs::read_dir(path)
        .unwrap_or_else(|err| panic!("read analyzer input dir {}: {err}", path.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .collect::<Vec<_>>();
    children.sort();

    for child in children {
        register_rerun_if_changed(&child);
    }
}

fn should_skip_csharp_artifact_path(path: &Path) -> bool {
    path.components()
        .any(|component| matches!(component.as_os_str().to_str(), Some("bin") | Some("obj")))
}

fn ensure_generated_lsp_resource_dir() {
    let resources_dir = ui_generated_lsp_resource_dir();
    fs::create_dir_all(&resources_dir).expect("create generated lsp-tools dir");
    let keep_file = resources_dir.join(".keep");
    if !keep_file.exists() {
        fs::write(&keep_file, b"generated by build.rs\n")
            .expect("create generated lsp-tools placeholder");
    }
}

fn maybe_prepare_bundled_lsp_assets() {
    if env::var("PROFILE").ok().as_deref() != Some("release") {
        return;
    }
    if env_flag_enabled("CODEPAPR_SKIP_BUNDLED_LSP_PREPARE") {
        println!("cargo:warning=skipping bundled desktop LSP preparation by env override");
        return;
    }

    prepare_bundled_lsp_assets().expect("prepare bundled desktop LSP assets");
    normalize_bundled_lsp_assets().expect("normalize bundled desktop LSP assets");
}

fn normalize_existing_bundled_lsp_assets() {
    let root = ui_generated_lsp_resource_dir();
    if !root.exists() {
        return;
    }
    normalize_bundled_lsp_assets().expect("normalize existing bundled desktop LSP assets");
}

fn prepare_bundled_lsp_assets() -> Result<(), String> {
    println!("cargo:warning=preparing bundled LSP assets: node runtime");
    ensure_bundled_node_runtime()?;
    println!("cargo:warning=preparing bundled LSP assets: node language packages");
    ensure_bundled_node_packages()?;
    println!("cargo:warning=preparing bundled LSP assets: python typeshed");
    ensure_bundled_typeshed()?;
    println!("cargo:warning=preparing bundled LSP assets: dotnet sdk");
    ensure_bundled_dotnet_sdk()?;
    println!("cargo:warning=preparing bundled LSP assets: csharp-ls");
    ensure_bundled_csharp_ls()?;
    println!("cargo:warning=preparing bundled LSP assets: java runtime + jdtls");
    ensure_bundled_java_support()?;
    println!("cargo:warning=preparing bundled LSP assets: clangd");
    ensure_bundled_clangd()?;
    println!("cargo:warning=preparing bundled LSP assets: sqls");
    ensure_bundled_sqls()?;
    println!("cargo:warning=preparing bundled LSP assets: marksman");
    ensure_bundled_marksman()?;
    println!("cargo:warning=preparing bundled LSP assets: rust-analyzer");
    ensure_bundled_rust_analyzer()?;
    println!("cargo:warning=preparing bundled LSP assets: gopls");
    ensure_bundled_gopls()?;
    println!("cargo:warning=preparing bundled LSP assets: manifest");
    write_bundle_manifest()?;
    Ok(())
}

fn maybe_publish_csharp_analyzer() {
    if env::var("PROFILE").ok().as_deref() != Some("release") {
        return;
    }

    let Ok(dotnet) = which_dotnet() else {
        println!("cargo:warning=dotnet not found; skipping bundled C# analyzer publish");
        return;
    };

    let manifest_dir = manifest_dir();
    let project = manifest_dir
        .join("tools")
        .join("CodePapr.CSharp.Analyzer")
        .join("CodePapr.CSharp.Analyzer.csproj");
    let output_dir = ui_generated_lsp_resource_dir().join("csharp-analyzer");
    fs::create_dir_all(&output_dir).expect("create csharp analyzer output dir");

    let dotnet_artifacts_dir = manifest_dir.join("target").join("csharp-analyzer-dotnet");
    let dotnet_output_dir = dotnet_artifacts_dir.join("bin");
    let dotnet_intermediate_dir = dotnet_artifacts_dir.join("obj");
    fs::create_dir_all(&dotnet_output_dir).expect("create dotnet analyzer output dir");
    fs::create_dir_all(&dotnet_intermediate_dir).expect("create dotnet analyzer intermediate dir");

    let runtime_identifier = runtime_identifier();
    let status = Command::new(dotnet)
        .arg("publish")
        .arg(&project)
        .arg("-c")
        .arg("Release")
        .arg("-o")
        .arg(&output_dir)
        .arg("-r")
        .arg(runtime_identifier)
        .arg(format!(
            "/p:BaseOutputPath={}",
            msbuild_property_path(&dotnet_output_dir)
        ))
        .arg(format!(
            "/p:BaseIntermediateOutputPath={}",
            msbuild_property_path(&dotnet_intermediate_dir)
        ))
        .arg("--self-contained")
        .arg("true")
        .arg("/p:PublishSingleFile=true")
        .arg("/p:PublishTrimmed=false")
        .arg("/p:DebugType=None")
        .status()
        .expect("run dotnet publish for csharp analyzer");

    if !status.success() {
        panic!("failed to publish bundled C# analyzer");
    }
}

fn ensure_bundled_node_runtime() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let runtime_dir = install_root.join("node-runtime");
    if managed_node_executable(&runtime_dir).is_some() {
        return Ok(());
    }

    if try_copy_from_managed_cache("node-runtime", &runtime_dir)?
        && managed_node_executable(&runtime_dir).is_some()
    {
        return Ok(());
    }

    let (url, archive_kind) = managed_node_download()?;
    install_archive(&url, archive_kind, &runtime_dir, "node-runtime")?;
    let node = managed_node_executable(&runtime_dir)
        .ok_or_else(|| "bundled node runtime missing executable after install".to_string())?;
    ensure_executable(&node)?;
    Ok(())
}

fn ensure_bundled_node_packages() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let packages_root = install_root.join("node-packages");
    if !packages_root.join("node_modules").is_dir() {
        let _ = try_copy_from_managed_cache("node-packages", &packages_root)?;
    }

    let node_runtime_root = install_root.join("node-runtime");
    let node = managed_node_executable(&node_runtime_root)
        .ok_or_else(|| "bundled node runtime executable missing".to_string())?;
    let npm_cli = managed_npm_cli(&node_runtime_root)
        .ok_or_else(|| "bundled npm-cli.js not found in managed node runtime".to_string())?;

    fs::create_dir_all(&packages_root)
        .map_err(|err| format!("create bundled node-packages dir: {err}"))?;

    let manifest = json!({
        "name": "codepapr-bundled-lsp-packages",
        "private": true,
        "description": "Bundled desktop LSP packages for CodePapr desktop release",
        "dependencies": bundled_node_package_versions()?,
    });
    let manifest_path = packages_root.join("package.json");
    fs::write(
        &manifest_path,
        serde_json::to_vec_pretty(&manifest)
            .map_err(|err| format!("serialize package.json: {err}"))?,
    )
    .map_err(|err| format!("write bundled node package.json: {err}"))?;

    let status = Command::new(&node)
        .arg(&npm_cli)
        .arg("install")
        .arg("--omit=dev")
        .arg("--no-audit")
        .arg("--no-fund")
        .current_dir(&packages_root)
        .status()
        .map_err(|err| {
            format!(
                "run npm install for bundled node packages with {} {}: {err}",
                node.display(),
                npm_cli.display()
            )
        })?;
    if !status.success() {
        return Err("npm install failed for bundled node packages".to_string());
    }

    for package_name in NODE_LSP_PACKAGES {
        let package_dir = packages_root.join("node_modules").join(package_name);
        if !package_dir.join("package.json").is_file() {
            return Err(format!(
                "missing bundled node package after install: {package_name}"
            ));
        }
    }

    Ok(())
}

fn ensure_bundled_java_support() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let java_root = install_root.join("java");
    let jdtls_root = java_root.join("jdtls");
    let jre_root = java_root.join("jre");

    if !java_root.exists() {
        println!("cargo:warning=java bundle: probing managed cache copy");
        let _ = try_copy_from_managed_cache("java", &java_root)?;
    }

    if find_jdtls_launcher(&jdtls_root).is_none() {
        println!("cargo:warning=java bundle: downloading/installing jdtls");
        install_archive(JDTLS_DOWNLOAD_URL, ArchiveKind::TarGz, &jdtls_root, "jdtls")?;
        println!("cargo:warning=java bundle: jdtls installed");
    }

    if managed_java_executable(&java_root).is_none() {
        println!("cargo:warning=java bundle: downloading/installing jre");
        let (url, archive_kind) = managed_java_download()?;
        install_archive(&url, archive_kind, &jre_root, "jre")?;
        let java = managed_java_executable(&java_root)
            .ok_or_else(|| "bundled java runtime missing executable after install".to_string())?;
        ensure_executable(&java)?;
        println!("cargo:warning=java bundle: jre installed");
    }

    println!("cargo:warning=java bundle: ready");
    Ok(())
}

fn ensure_bundled_clangd() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let clangd_root = install_root.join("clangd");
    let executable = clangd_root.join("bin").join(executable_name("clangd"));
    if executable.is_file() {
        ensure_executable(&executable)?;
        return Ok(());
    }

    if try_copy_from_managed_cache("clangd", &clangd_root)? {
        let copied_executable = clangd_root.join("bin").join(executable_name("clangd"));
        if copied_executable.is_file() {
            ensure_executable(&copied_executable)?;
            return Ok(());
        }
    }

    let (url, archive_kind) = managed_clangd_download()?;
    install_archive(&url, archive_kind, &clangd_root, "clangd")?;
    let executable = clangd_root.join("bin").join(executable_name("clangd"));
    if !executable.is_file() {
        return Err("bundled clangd missing executable after install".to_string());
    }
    ensure_executable(&executable)?;
    Ok(())
}

fn ensure_bundled_rust_analyzer() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let ra_root = install_root.join("rust-analyzer");
    let output_dir = ra_root.join("bin");
    let output_path = output_dir.join(executable_name("rust-analyzer"));
    if output_path.is_file() {
        ensure_executable(&output_path)?;
        return Ok(());
    }

    if try_copy_from_managed_cache("rust-analyzer", &ra_root)? {
        let copied = ra_root.join("bin").join(executable_name("rust-analyzer"));
        if copied.is_file() {
            ensure_executable(&copied)?;
            return Ok(());
        }
    }

    fs::create_dir_all(&output_dir)
        .map_err(|err| format!("create bundled rust-analyzer dir: {err}"))?;
    let source = ensure_rust_analyzer_on_builder()?;
    fs::copy(&source, &output_path)
        .map_err(|err| format!("copy rust-analyzer into bundled resources: {err}"))?;

    let lib_dir = ra_root.join("lib");
    let _ = fs::create_dir_all(&lib_dir);
    if let Some(parent) = source.parent().and_then(|p| p.parent()) {
        let src_lib = parent.join("lib");
        if src_lib.is_dir() {
            copy_path_recursive(&src_lib, &lib_dir)
                .map_err(|err| format!("copy rust-analyzer libs: {err}"))?;
        }
    }

    ensure_executable(&output_path)?;
    Ok(())
}

fn ensure_rust_analyzer_on_builder() -> Result<PathBuf, String> {
    if let Some(path) = rustup_which_rust_analyzer() {
        return Ok(path);
    }
    if let Some(path) = resolve_command_path("rust-analyzer") {
        return Ok(path);
    }
    if command_exists("rustup") {
        let status = Command::new("rustup")
            .arg("component")
            .arg("add")
            .arg("rust-analyzer")
            .status()
            .map_err(|err| format!("run rustup component add rust-analyzer: {err}"))?;
        if !status.success() {
            return Err("rustup component add rust-analyzer failed".to_string());
        }
        if let Some(path) = rustup_which_rust_analyzer() {
            return Ok(path);
        }
    }
    Err("rust-analyzer not available on builder".to_string())
}

fn rustup_which_rust_analyzer() -> Option<PathBuf> {
    if !command_exists("rustup") {
        return None;
    }
    let output = Command::new("rustup")
        .arg("which")
        .arg("rust-analyzer")
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let path = PathBuf::from(String::from_utf8_lossy(&output.stdout).trim().to_string());
    path.is_file().then_some(path)
}

fn ensure_bundled_sqls() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let sqls_root = install_root.join("sqls");
    let executable = sqls_root.join("bin").join(executable_name("sqls"));
    if executable.is_file() {
        ensure_executable(&executable)?;
        return Ok(());
    }
    if try_copy_from_managed_cache("sqls", &sqls_root)? {
        let copied = sqls_root.join("bin").join(executable_name("sqls"));
        if copied.is_file() {
            ensure_executable(&copied)?;
            return Ok(());
        }
    }
    let (url, archive_kind) = managed_sqls_download()?;
    install_archive(&url, archive_kind, &sqls_root, "sqls")?;
    bundle_single_binary(&sqls_root, "sqls")
}

fn ensure_bundled_marksman() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let marksman_root = install_root.join("marksman");
    let executable = marksman_root.join("bin").join(executable_name("marksman"));
    if executable.is_file() {
        ensure_executable(&executable)?;
        return Ok(());
    }

    if try_copy_from_managed_cache("marksman", &marksman_root)? {
        let copied = marksman_root.join("bin").join(executable_name("marksman"));
        if copied.is_file() {
            ensure_executable(&copied)?;
            return Ok(());
        }
    }

    let url = managed_marksman_url()?;
    let bin_dir = marksman_root.join("bin");
    fs::create_dir_all(&bin_dir)
        .map_err(|err| format!("create bundled marksman bin dir: {err}"))?;
    let dest = bin_dir.join(executable_name("marksman"));
    download_to_file(&url, &dest)?;
    verify_download(&url, &dest)?;
    ensure_executable(&dest)?;
    Ok(())
}

const DOTNET_SDK_VERSION: &str = "10.0.105";

fn ensure_bundled_dotnet_sdk() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let dotnet_root = install_root.join("dotnet-sdk");
    let dotnet_exe = dotnet_root.join(executable_name("dotnet"));
    if dotnet_exe.is_file() {
        ensure_executable(&dotnet_exe)?;
        return Ok(());
    }

    let (url, archive_kind) = dotnet_sdk_download()?;
    fs::create_dir_all(&dotnet_root)
        .map_err(|err| format!("create bundled dotnet sdk dir: {err}"))?;
    install_archive(&url, archive_kind, &dotnet_root, ".NET SDK")?;

    let exe = dotnet_root.join(executable_name("dotnet"));
    if !exe.is_file() {
        return Err("bundled dotnet sdk missing executable after install".to_string());
    }
    ensure_executable(&exe)?;
    Ok(())
}

fn dotnet_sdk_download() -> Result<(String, ArchiveKind), String> {
    let os = if target_os() == "macos" {
        "osx"
    } else if target_os() == "linux" {
        "linux"
    } else if target_os() == "windows" {
        "win"
    } else {
        return Err("unsupported target OS for bundled .NET SDK".to_string());
    };

    let arch = if target_arch() == "aarch64" {
        "arm64"
    } else if target_arch() == "x86_64" {
        "x64"
    } else {
        return Err("unsupported target arch for bundled .NET SDK".to_string());
    };

    let ext = if target_os() == "windows" {
        "zip"
    } else {
        "tar.gz"
    };
    let archive_kind = if target_os() == "windows" {
        ArchiveKind::Zip
    } else {
        ArchiveKind::TarGz
    };

    Ok((
        format!("https://dotnetcli.azureedge.net/dotnet/Sdk/{DOTNET_SDK_VERSION}/dotnet-sdk-{DOTNET_SDK_VERSION}-{os}-{arch}.{ext}"),
        archive_kind,
    ))
}

fn ensure_bundled_gopls() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let gopls_root = install_root.join("gopls");
    let target = gopls_root.join("bin").join(executable_name("gopls"));
    if target.is_file() {
        return ensure_executable(&target);
    }

    if try_copy_from_managed_cache("gopls", &gopls_root)? {
        let copied = gopls_root.join("bin").join(executable_name("gopls"));
        if copied.is_file() {
            return ensure_executable(&copied);
        }
    }

    let go_bin = which_go().unwrap_or_else(|| "go".to_string());
    let gopath = std::env::var("GOPATH").unwrap_or_else(|_| {
        let home = std::env::var("HOME").unwrap_or_default();
        format!("{home}/go")
    });
    let gopath_bin = std::path::Path::new(&gopath)
        .join("bin")
        .join(executable_name("gopls"));
    let _ = fs::create_dir_all(gopls_root.join("bin"));

    if gopath_bin.is_file() {
        let _ = fs::copy(&gopath_bin, &target);
        return ensure_executable(&target);
    }

    match std::process::Command::new(&go_bin)
        .args(["install", "golang.org/x/tools/gopls@latest"])
        .env(
            "GOBIN",
            gopls_root.join("bin").to_string_lossy().to_string(),
        )
        .output()
    {
        Ok(output) if output.status.success() => {
            if target.is_file() {
                return ensure_executable(&target);
            }
        }
        Ok(output) => {
            let stderr = String::from_utf8_lossy(&output.stderr);
            println!("cargo:warning=skipping bundled gopls (go install failed: {stderr})");
        }
        Err(e) => {
            println!("cargo:warning=skipping bundled gopls (go not available: {e})");
        }
    }
    Ok(())
}

fn ensure_bundled_csharp_ls() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let csharp_ls_root = install_root.join("csharp-ls");
    let target = csharp_ls_root
        .join("bin")
        .join(executable_name("csharp-ls"));
    if target.is_file() {
        return ensure_executable(&target);
    }

    if try_copy_from_managed_cache("csharp-ls", &csharp_ls_root)? {
        let copied = csharp_ls_root
            .join("bin")
            .join(executable_name("csharp-ls"));
        if copied.is_file() {
            return ensure_executable(&copied);
        }
    }

    let dotnet = install_root
        .join("dotnet-sdk")
        .join(executable_name("dotnet"));
    let tool_dir = csharp_ls_root.join("bin");
    fs::create_dir_all(&tool_dir).map_err(|err| format!("create bundled csharp-ls dir: {err}"))?;

    let status = Command::new(&dotnet)
        .arg("tool")
        .arg("install")
        .arg("csharp-ls")
        .arg("--tool-path")
        .arg(&tool_dir)
        .env("DOTNET_ROOT", install_root.join("dotnet-sdk"))
        .env("DOTNET_SKIP_FIRST_TIME_EXPERIENCE", "1")
        .env("DOTNET_CLI_TELEMETRY_OPTOUT", "1")
        .env("NUGET_XMLDOC_MODE", "skip")
        .status()
        .map_err(|err| format!("install csharp-ls: {err}"))?;

    if !status.success() {
        println!("cargo:warning=skipping bundled csharp-ls (dotnet tool install failed)");
        return Ok(());
    }

    if !target.is_file() {
        println!("cargo:warning=csharp-ls install succeeded but binary not found at expected path");
        return Ok(());
    }

    ensure_executable(&target)
}

fn ensure_bundled_typeshed() -> Result<(), String> {
    let install_root = ui_generated_lsp_resource_dir();
    let pyright_dist = install_root
        .join("node-packages")
        .join("node_modules")
        .join("pyright")
        .join("dist");
    let target_stdlib = pyright_dist.join("typeshed-fallback").join("stdlib");
    if target_stdlib.join("builtins.pyi").is_file() {
        return Ok(());
    }

    let url = "https://codeload.github.com/python/typeshed/tar.gz/refs/heads/main";
    let cache_dir = install_root.join("_typeshed");
    let _ = fs::create_dir_all(&cache_dir);
    let archive_path = cache_dir.join("typeshed-main.tar.gz");
    let extract_root = cache_dir.join("extract");

    if !archive_path.is_file() {
        download_to_file(url, &archive_path).map_err(|e| format!("download typeshed: {e}"))?;
        verify_download(url, &archive_path).map_err(|e| format!("verify typeshed: {e}"))?;
    }

    let _ = fs::remove_dir_all(&extract_root);
    fs::create_dir_all(&extract_root)
        .map_err(|err| format!("create typeshed extract dir: {err}"))?;
    extract_archive(&archive_path, ArchiveKind::TarGz, &extract_root)
        .map_err(|e| format!("extract typeshed: {e}"))?;

    let mut stdlib_src = None;
    for entry in std::fs::read_dir(&extract_root).map_err(|e| format!("read extract dir: {e}"))? {
        let path = entry.map_err(|e| format!("read entry: {e}"))?.path();
        if path.is_dir() {
            let stdlib = path.join("stdlib");
            if stdlib.join("builtins.pyi").is_file() {
                stdlib_src = Some(stdlib);
                break;
            }
        }
    }
    let src = stdlib_src
        .ok_or_else(|| format!("stdlib not found in typeshed extract at {:?}", extract_root))?;

    let parent = target_stdlib.parent().ok_or("no parent dir")?;
    fs::create_dir_all(parent).map_err(|e| format!("create target dir: {e}"))?;
    let _ = fs::remove_dir_all(&target_stdlib);
    copy_path_recursive(&src, &target_stdlib).map_err(|e| format!("copy typeshed: {e}"))?;

    if !target_stdlib.join("builtins.pyi").is_file() {
        return Err("typeshed builtins.pyi missing after copy".to_string());
    }
    Ok(())
}

fn which_go() -> Option<String> {
    if let Ok(output) = std::process::Command::new("go").arg("version").output() {
        if output.status.success() {
            return Some("go".to_string());
        }
    }
    if let Ok(output) = std::process::Command::new("go1.26.4")
        .arg("version")
        .output()
    {
        if output.status.success() {
            return Some("go1.26.4".to_string());
        }
    }
    None
}

fn bundle_single_binary(root: &Path, name: &str) -> Result<(), String> {
    let exe = executable_name(name);
    let bin_dir = root.join("bin");
    fs::create_dir_all(&bin_dir).map_err(|err| format!("create bundled {name} bin dir: {err}"))?;
    let dest = bin_dir.join(&exe);
    if dest.is_file() {
        return ensure_executable(&dest);
    }
    let mut found = None;
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        if dir == bin_dir {
            continue;
        }
        if let Ok(entries) = fs::read_dir(&dir) {
            for entry in entries.filter_map(|e| e.ok()) {
                let path = entry.path();
                if path.is_dir() {
                    stack.push(path);
                } else if path
                    .file_name()
                    .map(|n| n.to_string_lossy() == exe)
                    .unwrap_or(false)
                {
                    found = Some(path);
                    break;
                }
            }
        }
        if found.is_some() {
            break;
        }
    }
    let Some(source) = found else {
        return Err(format!("bundled {name} binary not found after extraction"));
    };
    fs::rename(&source, &dest).map_err(|err| format!("move bundled {name} binary: {err}"))?;
    ensure_executable(&dest)
}

fn managed_sqls_download() -> Result<(String, ArchiveKind), String> {
    let platform = if target_os() == "macos" {
        "darwin"
    } else if target_os() == "linux" {
        "linux"
    } else if target_os() == "windows" {
        "windows"
    } else {
        return Err("unsupported target OS for bundled sqls".to_string());
    };
    Ok((format!("https://github.com/sqls-server/sqls/releases/download/v{SQLS_VERSION}/sqls-{platform}-{SQLS_VERSION}.zip"), ArchiveKind::Zip))
}

fn managed_marksman_url() -> Result<String, String> {
    // linux 使用 musl 静态构建，兼容任意发行版；URL 与锁定清单一一对应。
    let name = if target_os() == "macos" {
        "marksman-macos".to_string()
    } else if target_os() == "linux" {
        let arch = if target_arch() == "aarch64" {
            "arm64"
        } else {
            "x64"
        };
        format!("marksman-linux-musl-{arch}")
    } else if target_os() == "windows" {
        "marksman.exe".to_string()
    } else {
        return Err("unsupported target OS for bundled marksman".to_string());
    };
    Ok(format!(
        "https://github.com/artempyanykh/marksman/releases/download/{MARKSMAN_VERSION}/{name}"
    ))
}

#[allow(dead_code)]
fn managed_marksman_download() -> Result<(String, ArchiveKind), String> {
    Err("marksman uses direct binary download, not archive".to_string())
}

fn bundled_node_package_versions() -> Result<serde_json::Map<String, Value>, String> {
    let lock_path = repo_root().join("package-lock.json");
    let lock = fs::read_to_string(&lock_path)
        .map_err(|err| format!("read package-lock.json for bundled node packages: {err}"))?;
    let parsed: Value =
        serde_json::from_str(&lock).map_err(|err| format!("parse package-lock.json: {err}"))?;
    let packages = parsed
        .get("packages")
        .and_then(Value::as_object)
        .ok_or_else(|| "package-lock.json missing packages section".to_string())?;

    let mut dependencies = serde_json::Map::new();
    for package_name in NODE_LSP_PACKAGES {
        let key = format!("node_modules/{package_name}");
        let version = packages
            .get(&key)
            .and_then(|value| value.get("version"))
            .and_then(Value::as_str)
            .unwrap_or("latest");
        dependencies.insert(
            (*package_name).to_string(),
            Value::String(version.to_string()),
        );
    }

    Ok(dependencies)
}

fn write_bundle_manifest() -> Result<(), String> {
    let manifest_path = ui_generated_lsp_resource_dir().join("bundle-manifest.json");
    let manifest = json!({
        "nodeRuntimeVersion": NODE_RUNTIME_VERSION,
        "clangdVersion": CLANGD_VERSION,
        "javaRuntimeVersion": JAVA_RUNTIME_VERSION,
        "nodePackages": bundled_node_package_versions()?,
    });
    fs::write(
        manifest_path,
        serde_json::to_vec_pretty(&manifest)
            .map_err(|err| format!("serialize bundle manifest: {err}"))?,
    )
    .map_err(|err| format!("write bundle manifest: {err}"))
}

fn normalize_bundled_lsp_assets() -> Result<(), String> {
    let root = ui_generated_lsp_resource_dir();
    flatten_nested_jre_home(&root)?;
    remove_nested_jre_codesign_artifacts(&root)?;
    remove_unused_node_bin_symlinks(&root)?;
    remove_jdtls_runtime_temp_files(&root)?;
    prune_deep_nested_bundle_paths(&root)?;
    normalize_tree_permissions(&root)?;
    clear_extended_attributes(&root)?;
    Ok(())
}

fn flatten_nested_jre_home(root: &Path) -> Result<(), String> {
    let jre_root = root.join("java").join("jre");
    let home_root = jre_root.join("Contents").join("Home");
    if !home_root.is_dir() {
        return Ok(());
    }

    let mut children = fs::read_dir(&home_root)
        .map_err(|err| format!("read nested JRE Home dir {}: {err}", home_root.display()))?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .collect::<Vec<_>>();
    children.sort();

    for child in children {
        let file_name = child
            .file_name()
            .ok_or_else(|| format!("missing file name for {}", child.display()))?;
        let destination = jre_root.join(file_name);
        if destination.exists() {
            continue;
        }
        fs::rename(&child, &destination).map_err(|err| {
            format!(
                "move nested JRE asset {} into {}: {err}",
                child.display(),
                destination.display()
            )
        })?;
    }

    let contents_root = jre_root.join("Contents");
    if contents_root.exists() {
        fs::remove_dir_all(&contents_root).map_err(|err| {
            format!(
                "remove nested JRE bundle structure {}: {err}",
                contents_root.display()
            )
        })?;
    }

    Ok(())
}

fn remove_nested_jre_codesign_artifacts(root: &Path) -> Result<(), String> {
    let codesign_dir = root
        .join("java")
        .join("jre")
        .join("Contents")
        .join("_CodeSignature");
    if codesign_dir.exists() {
        fs::remove_dir_all(&codesign_dir)
            .map_err(|err| format!("remove nested JRE _CodeSignature dir: {err}"))?;
    }
    Ok(())
}

fn remove_unused_node_bin_symlinks(root: &Path) -> Result<(), String> {
    let dot_bin = root.join("node-packages").join("node_modules").join(".bin");
    if dot_bin.exists() {
        fs::remove_dir_all(&dot_bin).map_err(|err| format!("remove node .bin dir: {err}"))?;
    }
    Ok(())
}

fn remove_jdtls_runtime_temp_files(root: &Path) -> Result<(), String> {
    let jdtls_config = root.join("java").join("jdtls").join("config_win");
    if !jdtls_config.is_dir() {
        return Ok(());
    }

    let mut manager_dirs = Vec::new();
    let mut stack = vec![jdtls_config];
    while let Some(dir) = stack.pop() {
        let entries = match fs::read_dir(&dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.filter_map(Result::ok) {
            let path = entry.path();
            if path.is_dir() {
                let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
                if name.starts_with(".manager") {
                    manager_dirs.push(path);
                } else {
                    stack.push(path);
                }
            }
        }
    }

    for dir in &manager_dirs {
        let _ = fs::remove_dir_all(dir);
        if dir.exists() {
            let _ = std::process::Command::new("cmd.exe")
                .args(["/c", "rd", "/s", "/q"])
                .arg(dir)
                .status();
        }
    }

    Ok(())
}

fn prune_deep_nested_bundle_paths(root: &Path) -> Result<(), String> {
    #[cfg(target_os = "windows")]
    {
        let test_dir = root
            .join("node-packages")
            .join("node_modules")
            .join("pyright")
            .join("dist")
            .join("typeshed-fallback")
            .join("stdlib")
            .join("@tests");
        if test_dir.exists() {
            let _ = fs::remove_dir_all(&test_dir);
            if test_dir.exists() {
                let _ = std::process::Command::new("cmd.exe")
                    .args(["/c", "rd", "/s", "/q"])
                    .arg(&test_dir)
                    .status();
            }
        }
    }

    let prune_targets: Vec<PathBuf> = vec![];
    for target in &prune_targets {
        if target.exists() {
            let _ = fs::remove_dir_all(target);
            // On Windows, deep paths may survive remove_dir_all; try again
            if target.exists() {
                let _ = std::process::Command::new("cmd.exe")
                    .args(["/c", "rd", "/s", "/q"])
                    .arg(target)
                    .status();
            }
        }
    }

    // Remove unnecessary files from node packages to reduce bundle size and
    // avoid NSIS path-length limits on Windows. LSP servers only need .js files.
    let node_modules = root.join("node-packages").join("node_modules");
    if node_modules.is_dir() {
        prune_node_module_extras(&node_modules)?;
    }

    Ok(())
}

fn prune_node_module_extras(root: &Path) -> Result<(), String> {
    let extensions_to_remove = [".d.ts", ".d.ts.map", ".js.map", ".tsbuildinfo"];
    let files_to_remove = ["CHANGELOG.md", "CHANGES.md", "HISTORY.md"];
    let dirs_to_remove = ["test", "tests", "__tests__", "docs", "examples"];

    let mut stack = vec![root.to_path_buf()];
    let mut dirs_to_prune = Vec::new();
    let mut nested_node_modules = Vec::new();

    while let Some(dir) = stack.pop() {
        let entries = match fs::read_dir(&dir) {
            Ok(entries) => entries,
            Err(_) => continue,
        };

        for entry in entries.filter_map(Result::ok) {
            let path = entry.path();
            let metadata = match fs::metadata(&path) {
                Ok(m) => m,
                Err(_) => continue,
            };

            if metadata.is_dir() {
                let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
                if dirs_to_remove.contains(&name) {
                    dirs_to_prune.push(path.clone());
                } else if name == "node_modules" && path != *root {
                    // Collect nested node_modules dirs to flatten
                    nested_node_modules.push(path.clone());
                } else {
                    stack.push(path);
                }
            } else if metadata.is_file() {
                let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
                let should_remove = extensions_to_remove.iter().any(|ext| name.ends_with(ext))
                    || files_to_remove.contains(&name);
                if should_remove {
                    let _ = fs::remove_file(&path);
                }
            }
        }
    }

    for dir in dirs_to_prune {
        let _ = fs::remove_dir_all(&dir);
    }

    // Flatten nested node_modules: move packages from nested node_modules
    // into the top-level node_modules to reduce path depth
    for nested in &nested_node_modules {
        flatten_nested_node_modules(root, nested);
    }

    Ok(())
}

fn flatten_nested_node_modules(top_level: &Path, nested: &Path) {
    let Ok(entries) = fs::read_dir(nested) else {
        return;
    };

    for entry in entries.filter_map(Result::ok) {
        let name = entry.file_name();
        let source = entry.path();
        let destination = top_level.join(&name);

        if destination.exists() {
            // Already exists at top level, skip
            continue;
        }

        // Try to move; if it fails (cross-device or other), try copy
        if fs::rename(&source, &destination).is_err() {
            let _ = copy_path_recursive(&source, &destination);
            let _ = fs::remove_dir_all(&source);
        }
    }

    // Remove the now-empty nested node_modules
    let _ = fs::remove_dir_all(nested);
}

fn normalize_tree_permissions(_root: &Path) -> Result<(), String> {
    #[cfg(unix)]
    {
        normalize_path_permissions(_root)?;
        for path in walk_paths(_root)? {
            normalize_path_permissions(&path)?;
        }
    }

    Ok(())
}

#[cfg(unix)]
fn normalize_path_permissions(_path: &Path) -> Result<(), String> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;

        let metadata = fs::symlink_metadata(_path)
            .map_err(|err| format!("read metadata {}: {err}", _path.display()))?;
        if metadata.file_type().is_symlink() {
            return Ok(());
        }

        let mode = metadata.permissions().mode();
        let normalized_mode = if metadata.is_dir() || mode & 0o111 != 0 {
            0o755
        } else {
            0o644
        };
        if mode != normalized_mode {
            fs::set_permissions(_path, fs::Permissions::from_mode(normalized_mode))
                .map_err(|err| format!("set permissions {}: {err}", _path.display()))?;
        }
    }

    Ok(())
}

fn clear_extended_attributes(_root: &Path) -> Result<(), String> {
    #[cfg(target_os = "macos")]
    {
        let status = Command::new("xattr")
            .arg("-cr")
            .arg(_root)
            .status()
            .map_err(|err| format!("run xattr -cr {}: {err}", _root.display()))?;
        if !status.success() {
            return Err(format!(
                "xattr -cr failed for bundled resources at {}",
                _root.display()
            ));
        }
    }

    Ok(())
}

#[cfg(unix)]
fn walk_paths(root: &Path) -> Result<Vec<PathBuf>, String> {
    let mut paths = Vec::new();
    walk_paths_into(root, &mut paths)?;
    Ok(paths)
}

#[cfg(unix)]
fn walk_paths_into(root: &Path, paths: &mut Vec<PathBuf>) -> Result<(), String> {
    let entries =
        fs::read_dir(root).map_err(|err| format!("read directory {}: {err}", root.display()))?;
    for entry in entries {
        let entry = entry.map_err(|err| format!("read dir entry {}: {err}", root.display()))?;
        let path = entry.path();
        paths.push(path.clone());
        let metadata = fs::symlink_metadata(&path)
            .map_err(|err| format!("read metadata {}: {err}", path.display()))?;
        if metadata.is_dir() && !metadata.file_type().is_symlink() {
            walk_paths_into(&path, paths)?;
        }
    }
    Ok(())
}

// ── Download checksum verification ────────────────────────────────────
// 校验实现与运行时共享 src/download_verification.rs（锁定清单 + 官方校验源）。

/// Verifies a downloaded file via the shared verification module.
///
/// - **Checksum mismatch** → hard error (build fails).
/// - **Checksum fetch failure** → warning (build continues, hash logged).
/// - **No checksum source** → warning with computed SHA-256.
///
/// Set `CODEPAPR_SKIP_DOWNLOAD_CHECKSUM=1` to bypass verification at build
/// time (development only). The runtime path has no such bypass.
fn verify_download(url: &str, file_path: &Path) -> Result<(), String> {
    if env_flag_enabled("CODEPAPR_SKIP_DOWNLOAD_CHECKSUM") {
        println!(
            "cargo:warning=skipping checksum verification (CODEPAPR_SKIP_DOWNLOAD_CHECKSUM=1)"
        );
        return Ok(());
    }

    match download_verification::verify_download(url, file_path) {
        Ok(outcome) => {
            println!(
                "cargo:warning=download verification: {url}: {}",
                outcome.description()
            );
            Ok(())
        }
        Err(err) => Err(format!("checksum verification failed for {url}: {err}")),
    }
}

fn install_archive(
    url: &str,
    archive_kind: ArchiveKind,
    destination: &Path,
    label: &str,
) -> Result<(), String> {
    let parent = destination
        .parent()
        .ok_or_else(|| format!("missing parent dir for {label}"))?;
    fs::create_dir_all(parent).map_err(|err| format!("create parent dir for {label}: {err}"))?;

    let archive_path = parent.join(format!(".{label}.download"));
    let stage_root = parent.join(format!(".{label}.stage"));
    let _ = fs::remove_file(&archive_path);
    let _ = fs::remove_dir_all(&stage_root);

    let install_result = (|| {
        download_to_file(url, &archive_path)?;
        verify_download(url, &archive_path)?;
        fs::create_dir_all(&stage_root).map_err(|err| format!("create staging dir: {err}"))?;
        extract_archive(&archive_path, archive_kind, &stage_root)?;
        let extracted_root = select_extracted_root(&stage_root)?;
        if destination.exists() {
            fs::remove_dir_all(destination).map_err(|err| {
                format!("remove old destination {}: {err}", destination.display())
            })?;
        }
        if extracted_root == stage_root {
            move_path_with_fallback(&stage_root, destination)?;
        } else {
            move_path_with_fallback(&extracted_root, destination)?;
            let _ = fs::remove_dir_all(&stage_root);
        }
        Ok(())
    })();

    let _ = fs::remove_file(&archive_path);
    let _ = fs::remove_dir_all(&stage_root);
    install_result
}

fn download_to_file(url: &str, target: &Path) -> Result<(), String> {
    const DOWNLOAD_RETRIES: usize = 3;

    let mut last_error = String::new();
    for attempt in 1..=DOWNLOAD_RETRIES {
        match download_to_file_once(url, target) {
            Ok(()) => return Ok(()),
            Err(err) => {
                last_error = err;
                if attempt < DOWNLOAD_RETRIES {
                    std::thread::sleep(Duration::from_secs(2));
                }
            }
        }
    }

    Err(format!(
        "download {url} failed after {DOWNLOAD_RETRIES} attempts: {last_error}"
    ))
}

#[cfg(not(windows))]
fn download_to_file_once(url: &str, target: &Path) -> Result<(), String> {
    let client = Client::builder()
        .timeout(DOWNLOAD_TIMEOUT)
        .user_agent("CodePapr-build/0.1")
        .redirect(reqwest::redirect::Policy::limited(10))
        .build()
        .map_err(|err| format!("build download client: {err}"))?;

    let mut response = client
        .get(url)
        .send()
        .map_err(|err| format!("download {url}: {err}"))?;
    if !response.status().is_success() {
        return Err(format!("download {url} returned {}", response.status()));
    }
    if let Some(length) = response.content_length() {
        if length > MAX_DOWNLOAD_BYTES as u64 {
            return Err(format!("download too large for {url}"));
        }
    }

    let mut file = fs::File::create(target)
        .map_err(|err| format!("create download file {}: {err}", target.display()))?;
    let mut downloaded = 0_usize;
    let started_at = Instant::now();
    let mut buffer = [0_u8; 16 * 1024];
    loop {
        if started_at.elapsed() > DOWNLOAD_TIMEOUT {
            return Err(format!(
                "download timed out for {url} after {} seconds",
                DOWNLOAD_TIMEOUT.as_secs()
            ));
        }

        let read = response
            .read(&mut buffer)
            .map_err(|err| format!("read response for {url}: {err}"))?;
        if read == 0 {
            break;
        }
        downloaded += read;
        if downloaded > MAX_DOWNLOAD_BYTES {
            return Err(format!("download too large for {url}"));
        }
        file.write_all(&buffer[..read])
            .map_err(|err| format!("write download file {}: {err}", target.display()))?;
    }

    Ok(())
}

#[cfg(windows)]
fn download_to_file_once(url: &str, target: &Path) -> Result<(), String> {
    download_to_file_with_powershell(url, target)
}

#[cfg(windows)]
fn download_to_file_with_powershell(url: &str, target: &Path) -> Result<(), String> {
    let target_str = target
        .to_string_lossy()
        .replace('\\', "/")
        .replace('"', "\\\"");
    let script = format!(
        "$ProgressPreference='SilentlyContinue'; Invoke-WebRequest -Uri \"{url}\" -OutFile \"{target}\"",
        target = target_str
    );
    let status = Command::new("powershell.exe")
        .arg("-NoProfile")
        .arg("-ExecutionPolicy")
        .arg("Bypass")
        .arg("-Command")
        .arg(script)
        .status()
        .map_err(|err| format!("run Invoke-WebRequest for {url}: {err}"))?;
    if !status.success() {
        return Err(format!("Invoke-WebRequest failed for {url}"));
    }

    let downloaded = fs::metadata(target)
        .map_err(|err| format!("stat download file {}: {err}", target.display()))?
        .len() as usize;
    if downloaded > MAX_DOWNLOAD_BYTES {
        return Err(format!("download too large for {url}"));
    }

    Ok(())
}

fn extract_archive(
    archive_path: &Path,
    archive_kind: ArchiveKind,
    destination: &Path,
) -> Result<(), String> {
    match archive_kind {
        ArchiveKind::TarGz => extract_tar_gz(archive_path, destination),
        ArchiveKind::TarXz => extract_tar_xz(archive_path, destination),
        ArchiveKind::Zip => extract_zip(archive_path, destination),
    }
}

fn extract_tar_gz(archive_path: &Path, destination: &Path) -> Result<(), String> {
    let archive_file = fs::File::open(archive_path)
        .map_err(|err| format!("open tar.gz {}: {err}", archive_path.display()))?;
    let decoder = GzDecoder::new(archive_file);
    Archive::new(decoder)
        .unpack(destination)
        .map_err(|err| format!("extract tar.gz {}: {err}", archive_path.display()))
}

fn extract_tar_xz(archive_path: &Path, destination: &Path) -> Result<(), String> {
    let archive_file = fs::File::open(archive_path)
        .map_err(|err| format!("open tar.xz {}: {err}", archive_path.display()))?;
    let decoder = XzDecoder::new(archive_file);
    Archive::new(decoder)
        .unpack(destination)
        .map_err(|err| format!("extract tar.xz {}: {err}", archive_path.display()))
}

fn extract_zip(archive_path: &Path, destination: &Path) -> Result<(), String> {
    let archive_file = fs::File::open(archive_path)
        .map_err(|err| format!("open zip {}: {err}", archive_path.display()))?;
    let mut archive = ZipArchive::new(archive_file)
        .map_err(|err| format!("read zip {}: {err}", archive_path.display()))?;

    for index in 0..archive.len() {
        let mut entry = archive
            .by_index(index)
            .map_err(|err| format!("read zip entry {index}: {err}"))?;
        let Some(entry_path) = entry.enclosed_name().map(|path| path.to_path_buf()) else {
            continue;
        };
        let target = destination.join(entry_path);
        if entry.is_dir() {
            fs::create_dir_all(&target)
                .map_err(|err| format!("create zip dir {}: {err}", target.display()))?;
            continue;
        }

        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)
                .map_err(|err| format!("create zip parent {}: {err}", parent.display()))?;
        }

        let mut file = fs::File::create(&target)
            .map_err(|err| format!("create zip file {}: {err}", target.display()))?;
        std::io::copy(&mut entry, &mut file)
            .map_err(|err| format!("write zip file {}: {err}", target.display()))?;

        #[cfg(unix)]
        if let Some(mode) = entry.unix_mode() {
            use std::os::unix::fs::PermissionsExt;
            let _ = fs::set_permissions(&target, fs::Permissions::from_mode(mode));
        }
    }

    Ok(())
}

fn select_extracted_root(stage_root: &Path) -> Result<PathBuf, String> {
    let entries = fs::read_dir(stage_root)
        .map_err(|err| format!("read staging dir {}: {err}", stage_root.display()))?
        .filter_map(Result::ok)
        .collect::<Vec<_>>();
    if entries.len() == 1 {
        let path = entries[0].path();
        if path.is_dir() {
            return Ok(path);
        }
    }
    Ok(stage_root.to_path_buf())
}

fn managed_node_download() -> Result<(String, ArchiveKind), String> {
    let (platform, archive_kind) = if target_os() == "macos" {
        ("darwin", ArchiveKind::TarGz)
    } else if target_os() == "linux" {
        ("linux", ArchiveKind::TarXz)
    } else if target_os() == "windows" {
        ("win", ArchiveKind::Zip)
    } else {
        return Err("unsupported target OS for bundled node runtime".to_string());
    };

    let arch = if target_arch() == "aarch64" {
        "arm64"
    } else if target_arch() == "x86_64" {
        "x64"
    } else {
        return Err("unsupported target arch for bundled node runtime".to_string());
    };

    let extension = match archive_kind {
        ArchiveKind::TarGz => "tar.gz",
        ArchiveKind::TarXz => "tar.xz",
        ArchiveKind::Zip => "zip",
    };

    Ok((
        format!(
            "https://nodejs.org/dist/{NODE_RUNTIME_VERSION}/node-{NODE_RUNTIME_VERSION}-{platform}-{arch}.{extension}"
        ),
        archive_kind,
    ))
}

fn managed_java_download() -> Result<(String, ArchiveKind), String> {
    let os = if target_os() == "macos" {
        "mac"
    } else if target_os() == "linux" {
        "linux"
    } else if target_os() == "windows" {
        "windows"
    } else {
        return Err("unsupported target OS for bundled java runtime".to_string());
    };

    let arch = if target_arch() == "aarch64" {
        "aarch64"
    } else if target_arch() == "x86_64" {
        "x64"
    } else {
        return Err("unsupported target arch for bundled java runtime".to_string());
    };

    let archive_kind = if target_os() == "windows" {
        ArchiveKind::Zip
    } else {
        ArchiveKind::TarGz
    };

    Ok((
        format!(
            "https://api.adoptium.net/v3/binary/latest/{JAVA_RUNTIME_VERSION}/ga/{os}/{arch}/jre/hotspot/normal/eclipse"
        ),
        archive_kind,
    ))
}

fn managed_clangd_download() -> Result<(String, ArchiveKind), String> {
    let platform = if target_os() == "macos" {
        "mac"
    } else if target_os() == "linux" {
        if target_arch() != "x86_64" {
            return Err("unsupported Linux target arch for bundled clangd".to_string());
        }
        "linux"
    } else if target_os() == "windows" {
        if target_arch() != "x86_64" {
            return Err("unsupported Windows target arch for bundled clangd".to_string());
        }
        "windows"
    } else {
        return Err("unsupported target OS for bundled clangd".to_string());
    };

    Ok((
        format!(
            "https://github.com/clangd/clangd/releases/download/{CLANGD_VERSION}/clangd-{platform}-{CLANGD_VERSION}.zip"
        ),
        ArchiveKind::Zip,
    ))
}

fn managed_node_executable(runtime_root: &Path) -> Option<PathBuf> {
    [
        runtime_root.join("bin").join(executable_name("node")),
        runtime_root.join(executable_name("node")),
    ]
    .into_iter()
    .find(|path| path.is_file())
}

fn managed_npm_cli(runtime_root: &Path) -> Option<PathBuf> {
    [
        runtime_root
            .join("node_modules")
            .join("npm")
            .join("bin")
            .join("npm-cli.js"),
        runtime_root
            .join("lib")
            .join("node_modules")
            .join("npm")
            .join("bin")
            .join("npm-cli.js"),
    ]
    .into_iter()
    .find(|path| path.is_file())
}

fn managed_java_executable(java_root: &Path) -> Option<PathBuf> {
    [
        java_root
            .join("jre")
            .join("bin")
            .join(executable_name("java")),
        java_root
            .join("jre")
            .join("Contents")
            .join("Home")
            .join("bin")
            .join(executable_name("java")),
        java_root.join("bin").join(executable_name("java")),
    ]
    .into_iter()
    .find(|path| path.is_file())
}

fn find_jdtls_launcher(jdtls_root: &Path) -> Option<PathBuf> {
    let entries = fs::read_dir(jdtls_root.join("plugins")).ok()?;
    entries
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .find(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .map(|name| {
                    name.starts_with("org.eclipse.equinox.launcher_") && name.ends_with(".jar")
                })
                .unwrap_or(false)
        })
}

fn ensure_executable(_path: &Path) -> Result<(), String> {
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;

        let metadata = fs::metadata(_path)
            .map_err(|err| format!("read metadata {}: {err}", _path.display()))?;
        let mode = metadata.permissions().mode();
        if mode & 0o111 == 0 {
            fs::set_permissions(_path, fs::Permissions::from_mode(mode | 0o755))
                .map_err(|err| format!("set executable bit {}: {err}", _path.display()))?;
        }
    }

    Ok(())
}

fn managed_cache_lsp_root() -> Option<PathBuf> {
    let home = env::var_os("HOME").filter(|value| !value.is_empty());
    if let Some(home) = home {
        return Some(PathBuf::from(home).join(".codepapr").join("lsp-tools"));
    }

    env::var_os("USERPROFILE")
        .filter(|value| !value.is_empty())
        .map(|profile| PathBuf::from(profile).join(".codepapr").join("lsp-tools"))
}

fn try_copy_from_managed_cache(relative: &str, destination: &Path) -> Result<bool, String> {
    let Some(cache_root) = managed_cache_lsp_root() else {
        return Ok(false);
    };
    let source = cache_root.join(relative);
    if !source.exists() {
        return Ok(false);
    }

    copy_path_recursive(&source, destination)?;
    Ok(true)
}

fn copy_path_recursive(source: &Path, destination: &Path) -> Result<(), String> {
    if source.is_file() {
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)
                .map_err(|err| format!("create destination parent {}: {err}", parent.display()))?;
        }
        fs::copy(source, destination).map_err(|err| {
            format!(
                "copy file {} to {}: {err}",
                source.display(),
                destination.display()
            )
        })?;
        return Ok(());
    }

    if !source.is_dir() {
        return Ok(());
    }

    fs::create_dir_all(destination)
        .map_err(|err| format!("create destination dir {}: {err}", destination.display()))?;
    for entry in fs::read_dir(source)
        .map_err(|err| format!("read source dir {}: {err}", source.display()))?
    {
        let entry =
            entry.map_err(|err| format!("read source entry {}: {err}", source.display()))?;
        let child_source = entry.path();
        let child_destination = destination.join(entry.file_name());
        copy_path_recursive(&child_source, &child_destination)?;
    }

    Ok(())
}

fn move_path_with_fallback(source: &Path, destination: &Path) -> Result<(), String> {
    match fs::rename(source, destination) {
        Ok(()) => Ok(()),
        Err(rename_err) => {
            copy_path_recursive(source, destination).map_err(|copy_err| {
                format!(
                    "move {} to {} failed ({rename_err}); copy fallback failed: {copy_err}",
                    source.display(),
                    destination.display()
                )
            })?;

            if source.is_dir() {
                fs::remove_dir_all(source).map_err(|cleanup_err| {
                    format!(
                        "move {} to {} used copy fallback but cleanup failed: {cleanup_err}",
                        source.display(),
                        destination.display()
                    )
                })?;
            } else if source.exists() {
                fs::remove_file(source).map_err(|cleanup_err| {
                    format!(
                        "move {} to {} used copy fallback but file cleanup failed: {cleanup_err}",
                        source.display(),
                        destination.display()
                    )
                })?;
            }

            Ok(())
        }
    }
}

fn manifest_dir() -> PathBuf {
    PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"))
}

fn repo_root() -> PathBuf {
    manifest_dir()
        .parent()
        .expect("src-tauri should have a parent ui directory")
        .parent()
        .expect("ui directory should have a parent scope directory")
        .parent()
        .expect("scope directory should have a parent packages directory")
        .parent()
        .expect("packages directory should have a parent repo root")
        .to_path_buf()
}

fn ui_generated_lsp_resource_dir() -> PathBuf {
    if let Ok(custom) = env::var("CODEPAPR_BUNDLED_LSP_DIR") {
        let path = PathBuf::from(custom);
        let _ = fs::create_dir_all(&path);
        return path;
    }

    manifest_dir()
        .parent()
        .expect("src-tauri should have a parent ui directory")
        .join("generated")
        .join("lsp-tools")
}

fn msbuild_property_path(path: &Path) -> String {
    let mut normalized = path.to_string_lossy().replace('\\', "/");
    if !normalized.ends_with('/') {
        normalized.push('/');
    }
    normalized
}

fn which_dotnet() -> Result<String, ()> {
    let candidate = if cfg!(windows) {
        "dotnet.exe"
    } else {
        "dotnet"
    };
    let status = Command::new(candidate).arg("--info").status();
    match status {
        Ok(result) if result.success() => Ok(candidate.to_string()),
        _ => Err(()),
    }
}

fn executable_name(base: &str) -> String {
    if cfg!(windows) {
        format!("{base}.exe")
    } else {
        base.to_string()
    }
}

fn command_exists(command: &str) -> bool {
    resolve_command_path(command).is_some()
}

fn resolve_command_path(command: &str) -> Option<PathBuf> {
    let path = Path::new(command);
    if path.components().count() > 1 {
        return path.is_file().then(|| path.to_path_buf());
    }

    let extensions = if cfg!(windows) {
        env::var("PATHEXT")
            .unwrap_or_else(|_| ".COM;.EXE;.BAT;.CMD".to_string())
            .split(';')
            .map(|entry| entry.trim().to_string())
            .filter(|entry| !entry.is_empty())
            .collect::<Vec<_>>()
    } else {
        vec![String::new()]
    };

    let command_has_extension = Path::new(command).extension().is_some();

    env::var_os("PATH").and_then(|paths| {
        env::split_paths(&paths).find_map(|dir| {
            if command_has_extension {
                let explicit = dir.join(command);
                if explicit.is_file() {
                    return Some(explicit);
                }
            }

            extensions.iter().find_map(|extension| {
                let candidate = if extension.is_empty() {
                    dir.join(command)
                } else {
                    dir.join(format!("{command}{extension}"))
                };
                candidate.is_file().then_some(candidate)
            })
        })
    })
}

fn env_flag_enabled(name: &str) -> bool {
    env::var(name)
        .map(|value| {
            let normalized = value.trim().to_ascii_lowercase();
            matches!(normalized.as_str(), "1" | "true" | "yes" | "on")
        })
        .unwrap_or(false)
}

fn target_os() -> String {
    env::var("CARGO_CFG_TARGET_OS").expect("missing CARGO_CFG_TARGET_OS")
}

fn target_arch() -> String {
    env::var("CARGO_CFG_TARGET_ARCH").expect("missing CARGO_CFG_TARGET_ARCH")
}

fn runtime_identifier() -> &'static str {
    match (
        env::var("CARGO_CFG_TARGET_OS").ok().as_deref(),
        env::var("CARGO_CFG_TARGET_ARCH").ok().as_deref(),
    ) {
        (Some("macos"), Some("aarch64")) => "osx-arm64",
        (Some("macos"), Some("x86_64")) => "osx-x64",
        (Some("windows"), Some("aarch64")) => "win-arm64",
        (Some("windows"), Some("x86_64")) => "win-x64",
        (Some("linux"), Some("aarch64")) => "linux-arm64",
        (Some("linux"), Some("x86_64")) => "linux-x64",
        other => panic!("unsupported target for bundled C# analyzer: {other:?}"),
    }
}
