import type { GitFileSelection } from './utils/workspaceGitPanel';
import type { ReviewScope } from './utils/codeReview';
import type { PreviewLocation } from './utils/projectDiagnosticLocations';
import { getTranslation, type Lang } from './utils/i18n';

export type AppMainProps = {
  projectGraphLoading: boolean;
  projectGraphPhase: null | { phase: string; current: number; total: number };
  workspacePath: string;
  t: ReturnType<typeof getTranslation>;
  openedAppId: string | null;
  isGitPanelExpanded: boolean;
  settings: { lang: Lang; experimentalCharacters?: boolean };
  selectedPath: string | null;
  selectedGitFile: GitFileSelection | null;
  handleSelectPath: (path: string | null) => void;
  setSelectedPath: (path: string | null) => void;
  setSelectedDiagnosticLocation: (loc: PreviewLocation | null) => void;
  setSelectedGitFile: (file: GitFileSelection | null) => void;
  setActiveMainTab: (tab: 'chat' | 'code') => void;
  setShowCodeReview: (scope: ReviewScope | null) => void;
  setIsGitPanelExpanded: (v: boolean) => void;
  workbenchHidden: boolean;
  dockedPluginId: string | null;
  setShowSettings: (v: boolean) => void;
  setShowCharacters: (v: boolean) => void;
  setShowStats: (v: boolean) => void;
  setShowAbout: (v: boolean) => void;
  handleNavigateToLocation: (location: PreviewLocation) => void;
  activeMainTab: 'chat' | 'code';
  selectedFileName: string | null;
  handleCloseCodeTab: () => void;
  selectedDiagnosticLocation: PreviewLocation | null;
  showSettings: boolean;
  showCharacters: boolean;
  showAbout: boolean;
  showProjectSwitcher: boolean;
  setShowProjectSwitcher: (v: boolean) => void;
  showStats: boolean;
  showProjectConfig: boolean;
  setShowProjectConfig: (v: boolean) => void;
  setShowSkillMarket: (v: boolean) => void;
  showSkillMarket: boolean;
  showCodeReview: ReviewScope | null;
  settingsLoaded: boolean;
  onboardingDismissed: boolean;
  setOnboardingDismissed: (v: boolean) => void;
  nativeLayerBlocked: boolean;
  activePreviewSession: { workspacePath: string } | null;
  browserPanelOpen: boolean;
  browserEngine: string;
  openBrowserPanel: () => void;
  setWorkbenchHidden: (v: boolean) => void;
};
