import type { Lang } from '../utils/i18n';
import type { PaprAppListing } from '../utils/marketAppTypes';

export function copy(lang: Lang | undefined) {
  if (lang === 'en') {
    return {
      title: 'App & Plugin Marketplace',
      subtitle: 'Discover and install native UI micro-apps, visual canvases, and overlay plugins.',
      source: 'Source',
      appsRegistry: 'Official Apps Repository',
      searchApps: 'Search apps & plugins...',
      filterAll: 'All',
      filterPlugins: 'Plugins',
      filterApps: 'Standalone Apps',
      install: 'Install',
      installGlobal: 'Install Globally',
      installWorkspace: 'Install to Project',
      installing: 'Installing...',
      installed: 'Installed',
      installedGlobal: 'Global',
      installedWorkspace: 'Project',
      installError: 'Install failed',
      loading: 'Loading market apps...',
      empty: 'No apps or plugins found.',
      error: 'Failed to load app marketplace data.',
      retry: 'Retry',
      close: 'Close',
      detail: 'Details',
      features: 'Features',
      repository: 'Repository',
      website: 'Website',
      noWorkspace: 'Open a project workspace first to install to project.',
      noWorkspaceOpen: 'No workspace open (Global install only)',
      tags: 'Tags',
      allTags: 'All',
      back: 'Back to results',
      update: 'Update',
      updateAvailable: 'Update available',
      uninstall: 'Uninstall',
      uninstalling: 'Uninstalling...',
      openApp: 'Open',
      pinPlugin: 'Show / Pin',
      appInstalledSuccess: (title: string, scope: string) =>
        `${title} installed successfully (${scope === 'global' ? 'Global' : 'Project'})`,
      uninstallSuccess: (title: string) => `${title} uninstalled`,
      uninstallConfirm: (title: string, isPlugin?: boolean) =>
        isPlugin ? `Uninstall plugin "${title}"?` : `Uninstall "${title}"?`,
      uninstallConfirmBody: 'This permanently removes its files and local data (including papr.db). This cannot be undone.',
      uninstallConfirmCancel: 'Cancel',
      uninstallConfirmAction: 'Uninstall',
      surfaceConfig: 'Surface & Window Layout',
      permissions: 'Permissions & Security',
      networkAccess: 'Network Access',
      workspaceAccess: 'Workspace Access',
      dataStorage: 'Data Storage',
      storageDesc: 'Isolated per app and per project (SQLite papr.db)',
      enabled: 'Direct fetch/API allowed',
      disabled: 'Disabled (Sandbox)',
    };
  }
  if (lang === 'zh-TW') {
    return {
      title: '應用與外掛市場',
      subtitle: '探索並安裝原生 UI 微應用、視覺化看板與桌面浮窗外掛。',
      source: '來源',
      appsRegistry: '官方外掛庫',
      searchApps: '搜尋應用與外掛...',
      filterAll: '全部',
      filterPlugins: '外掛 (Plugins)',
      filterApps: '獨立應用 (Apps)',
      install: '安裝',
      installGlobal: '全域安裝 (所有專案)',
      installWorkspace: '專案安裝 (僅目前)',
      installing: '安裝中...',
      installed: '已安裝',
      installedGlobal: '全域',
      installedWorkspace: '專案',
      installError: '安裝失敗',
      loading: '載入應用市場中...',
      empty: '沒有找到符合的應用或外掛。',
      error: '載入失敗。',
      retry: '重試',
      close: '關閉',
      detail: '詳情',
      features: '功能',
      repository: '倉庫',
      website: '網站',
      noWorkspace: '請先開啟專案工作區再安裝到專案。',
      noWorkspaceOpen: '尚未開啟工作區（僅支援全域安裝）',
      tags: '標籤',
      allTags: '全部',
      back: '返回結果',
      update: '更新',
      updateAvailable: '有新版本',
      uninstall: '卸載',
      uninstalling: '卸載中...',
      openApp: '開啟',
      pinPlugin: '顯示 / 置頂',
      appInstalledSuccess: (title: string, scope: string) =>
        `${title} 安裝成功 (${scope === 'global' ? '全域' : '專案'})`,
      uninstallSuccess: (title: string) => `已卸載 ${title}`,
      uninstallConfirm: (title: string, isPlugin?: boolean) =>
        isPlugin ? `確定卸載外掛「${title}」？` : `確定卸載「${title}」？`,
      uninstallConfirmBody: '將永久刪除其檔案與本地資料（含 papr.db）。此操作無法撤銷。',
      uninstallConfirmCancel: '取消',
      uninstallConfirmAction: '卸載',
      surfaceConfig: '介面與佈局配置',
      permissions: '權限與安全性',
      networkAccess: '網路存取',
      workspaceAccess: '工作區檔案存取',
      dataStorage: '資料儲存',
      storageDesc: '按應用、按專案隔離儲存 (SQLite papr.db)',
      enabled: '允許直接網路連線/API',
      disabled: '已停用（沙箱防護）',
    };
  }
  return {
    title: '应用与插件市场',
    subtitle: '探索并安装原生 UI 微应用、可视化看板与桌面悬浮插件。',
    source: '来源',
    appsRegistry: '官方插件库',
    searchApps: '搜索应用与插件...',
    filterAll: '全部',
    filterPlugins: '插件 (Plugins)',
    filterApps: '独立应用 (Apps)',
    install: '安装',
    installGlobal: '全局安装 (所有项目)',
    installWorkspace: '项目安装 (仅当前)',
    installing: '安装中...',
    installed: '已安装',
    installedGlobal: '全局',
    installedWorkspace: '项目',
    installError: '安装失败',
    loading: '加载应用市场中...',
    empty: '没有找到符合的应用或插件。',
    error: '加载失败。',
    retry: '重试',
    close: '关闭',
    detail: '详情',
    features: '功能',
    repository: '仓库',
    website: '网站',
    noWorkspace: '请先打开项目工作区再安装到项目。',
    noWorkspaceOpen: '尚未打开工作区（仅支持全局安装）',
    tags: '标签',
    allTags: '全部',
    back: '返回结果',
      update: '更新',
      updateAvailable: '有新版本',
      uninstall: '卸载',
    uninstalling: '卸载中...',
    openApp: '打开',
    pinPlugin: '显示 / 置顶',
    appInstalledSuccess: (title: string, scope: string) =>
      `${title} 安装成功 (${scope === 'global' ? '全局' : '项目'})`,
    uninstallSuccess: (title: string) => `已卸载 ${title}`,
    uninstallConfirm: (title: string, isPlugin?: boolean) =>
      isPlugin ? `确定卸载插件「${title}」？` : `确定卸载「${title}」？`,
    uninstallConfirmBody: '将永久删除其文件和本地数据（含 papr.db）。此操作无法撤销。',
    uninstallConfirmCancel: '取消',
    uninstallConfirmAction: '卸载',
    surfaceConfig: '界面与布局配置',
    permissions: '权限与安全性',
    networkAccess: '网络访问',
    workspaceAccess: '工作区文件访问',
    dataStorage: '数据存储',
      storageDesc: '按应用、按项目隔离存储 (SQLite papr.db)',
    enabled: '允许直接网络请求/API',
    disabled: '已禁用（沙箱保护）',
  };
}

export function listingTitle(listing: PaprAppListing, lang: Lang | undefined): string {
  if (lang === 'en' && listing.titleEn) return listing.titleEn;
  return listing.title || listing.name;
}

export function listingDescription(listing: PaprAppListing, lang: Lang | undefined): string {
  if (lang === 'en' && listing.descriptionEn) return listing.descriptionEn;
  return listing.description;
}


export type MarketCopy = ReturnType<typeof copy>;
